_commit: v0.1.0-14-g04294ae
_src_path: git@github.com:benwebber/open-data-toronto-copier.git
name: BodySafe
project: open-data-toronto-bodysafe
repo: benwebber/open-data-toronto-bodysafe
slug: bodysafe
url: https://open.toronto.ca/dataset/bodysafe/
