---
name: Fetch latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      uses: benwebber/get-ckan-package@v1
      with:
        url: https://ckan0.cf.opendata.inter.prod-toronto.ca/
        package_id: c4052ff7-a09d-4eaf-84e6-6669519f413d
        output_dir: data
        resource_ids: '["f9f84603-973c-43eb-bed0-a0ec26a2652b"]'
    - name: Push latest data
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data
        git commit -m 'Update BodySafe data' || exit
        git push
